module Falcom
class Discname < Model
  many_to_one :album, :key => :albumid
end
end

# Table: discnames
# Columns:
#  id      | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  albumid | integer |
#  number  | integer |
#  name    | text    |
# Indexes:
#  discnames_pkey | PRIMARY KEY btree (id)
