module Falcom
class Mediatype < Model
  one_to_many :media, :key=>:mediatypeid, :order=>:publicationdate
end
end

# Table: mediatypes
# Columns:
#  id   | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name | text    |
# Indexes:
#  mediatypes_pkey | PRIMARY KEY btree (id)
