module Falcom
class Series < Model
  many_to_many :albums, :left_key=>:seriesid, :join_table=>:seriesalbums, :right_key=>:albumid, :order=>:sortname, :clearer=>nil
  one_to_many :games, :key=>:seriesid, :order=>:name, :read_only=>true
end
end

# Table: series
# Columns:
#  id   | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name | text    |
# Indexes:
#  series_pkey | PRIMARY KEY btree (id)
